### ISSUE TITLE
WhereAmI is now part of the EVCloudKitDao demo app

### ISSUE THREAD

**Issue by evermeer** [lypiut/WhereAmI#1]
Just wanted to let you know that WhereAmI is now part of the demo app for https://github.com/evermeer/EVCloudKitDao
Making it possible to send a location update

One remark, You do not need to write out the complete block specification. Its enough to call it like this:
        WhereAmI.sharedInstance.whereAmI({ location in
        }, locationRefusedHandler: {locationIsAuthorized in 
        });

And then why does the locationRefusedHandler has the parameter locationIsAuthorized? It's always false isn't it?

**Comment by lypiut** [comment]
Hi @evermeer ,

thank for the integration into your demo app :)
And yes you right the `locationIsAuthorized` is useless, I was a little bit tired when I wrote this method.   An update is coming and the `locationRefusedHandler` closure will no have parameter and look like this:

```
WhereAmI.sharedInstance.whereAmI({ (location) -> Void in
             // Put code here
        }, locationRefusedHandler: { () -> Void in
             // Put code here
});
```

**Comment by evermeer** [comment]
Good to hear that you will continue to refine this lib. its extreamly easy to use. I will definitly keep on using it. thanks!

**Comment by lypiut** [comment]
The [1.1.0](https://github.com/lypiut/WhereAmI/releases/tag/1.1.0) version is released and contains the `locationRefusedHandler` improvement.
