### ISSUE TITLE
Locating user take significant time

### ISSUE THREAD

**Issue by staticdreams** [lypiut/WhereAmI#11]
I'm using this library since iOS 8 and on iOS 8 it worked great a fast. I started noticing that locating time increased on iOS9. Thought, maybe my GPS coverage got worse, but it turns out it wasn't the case.

I compared locating user with another library "SwiftLocation". Actually they were performing user locating side by side. WhereAmI now takes up to 8-9 seconds to locate the user, which wasn't the case before, where as the other library took like 0.5 seconds or so. 

Are there any significant changed in locating user in iOS9 we should be aware of, has anything changed? Also, has anyone else noticed increased time for locating the user recently?

**Comment by lypiut** [comment]
Hi,

Thank for reporting this issue. The code doesn't evolve so much and run fine on my device. 

On which device are you running your test ?

I will run a couple of test on my devices and try to figure out your problem.

**Comment by staticdreams** [comment]
I'm running it on iPhone 6s..

**Comment by lypiut** [comment]
Hi,
Sorry for the late response I was busy these days. 
I made several test, I figured out where the problem come, my _locationPrecision_ profils are too strict.

You can try to change the value of \* horizontalAccuracy*, 500 meters by default, to something like 1000 or 1500.

I will to improve the default configuration in a futur update.
