### ISSUE TITLE
Location often fails

### ISSUE THREAD

**Issue by staticdreams** [lypiut/WhereAmI#2]
Hi!

I'm using WhereAmI to get user location. Really easy to use and straightforward. So thank you for that.
However, I often experience problems detecting location. Without changing location detection code I would say I'm getting 50-50% chance when launching in the Simulator. I thought I'm using the extension incorrectly, but I'm getting same thing with your Example app.

Have you experience anything similar? Or maybe with the new Xcode there is some sort of a limit on how often you can request the location?

My simulator is set to use custom coordinates. Xcode also is set to simulate a particular location.. I don't see where this might be coming from.

**Comment by lypiut** [comment]
Hi @staticdreams,

Have you try on a real device ? 
Since iOS 8 I discovered that the iOS simulator bug sometime when you set and save a custom location. You need to set the location on `none` and put back your custom location. 

That's why I run all my tests which need user's location on my iPhone and iPad :)

**Comment by staticdreams** [comment]
Actually on my device it was even worse.. I couldn't get a "recent location fix" meaning it failed to locate user within the validity timeframe..
I really really want to be able to use your extension, but the most reliable way for me to get a location was the original way of implementing all the delegates myself .. Thanks anyway

**Comment by lypiut** [comment]
Hum, it's really strange.
I made several try in a test app with different devices and all works fine.
Have you change any settings ? Can you give me information about the device used (model, OS, jailbroken) ?
Thank

**Comment by SebastienMichoy** [comment]
Hi @staticdreams & @lypiut.

I just tried the example app on several devices and I didn't have any problem.
Here is the list of devices on which I tried:

| Model | Version |
| --- | --- |
| iPhone 4 | 7.1.2 (11D257) |
| iPhone 5 | 8.1.3 (12B466) |
| iPhone 5S | 7.0.5 (11B601) |
| iPhone 6 Plus | 8.0 (12A366) |
| iPad Air 2 (Model A1566) | 8.1 (12B410) |

@staticdreams, which device do you use?

**Comment by staticdreams** [comment]
@lypiut @SebastienMichoy I use jailbroken iPhone 6 (iOS 8.1)
Nothing simply happens when I run the closure.. 
I gotta admit I tried more on the simulator than on real device. Simulator run iOS 8.2
Also I noticed that it is likely to fail on the first launch (when advice asks if it can use the location) and silently fails. On consecutive launches the chance of detect location is about 30%.  As I stated earlier, both my Simulator and Xcode are simulating location.

**Comment by staticdreams** [comment]
Here's a simple demonstration how a simulator would fail on fresh simulator
![mar 17 2015 15 44](https://cloud.githubusercontent.com/assets/988705/6689813/e7f1b916-ccbc-11e4-8ab8-fe5c1c77e172.gif)

Maybe I should stop using Simulator, although its pretty handy for development.. I guess its Xcode issue

**Comment by lypiut** [comment]
With a fresh simulator I had the same problem on my first try. 
It's a simulator random bug, to solve it set the simulator's location to `None` and after set a `Custom location`.

**Comment by staticdreams** [comment]
Ok, I understand what was wrong now on the actual device. It fails to get a fix when indoors and wifi is off. Is there a way to handle this kind of situations?

I mean some kind of error handling. otherwise there is just nothing happening on the screen

**Comment by lypiut** [comment]
By default the library calls the closure when the horizontal accuracy is under 200 meters. 
So if your location precision never goes under 200 meters, the closure will never be called.
You can take a look to the different location profiles provided, or you can change the `horizontalAccuracy` parameter.

For the next update I will tune the location profiles.
