### ISSUE TITLE
WhereAmI crashes with NSInternalInconsistency on iOS 9

### ISSUE THREAD

**Issue by nanoxd** [lypiut/WhereAmI#8]
WhereAmI crashes on iOS 9 with an `NSInternalInconsistency` because the delegate did not implement the `locationManager:didFailWithError` function. Looking at the headers, the function itself is optional. Do you have any idea why this is caused? 

It can be reproduced using the sample app on iOS 9 GM. Implementing the function alone allows the app to continue functioning and ultimately provide location data.

**Comment by staticdreams** [comment]
I've got the exact same issue after upgrading to Swift 2.0 and Xcode 7. My app just crashes on startup (that's when I'm trying to get location)

**Comment by lypiut** [comment]
Hi,

Thank for the report, I was pretty busy theses days. This bug is weird but I implement the didFailWithError delegate function. The fix is available on the Swift 2.0 branch. I will release the new version of WhereAmI this week.
